import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import Header from '@/components/Header';
import Footer from '@/components/Footer';
import Provider from '@/components/Provider';
import { FormProvider } from '@/components/FormProvider';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en">
			<body
				className={`${inter.className} flex flex-col justify-center min-h-screen h-full`}
			>
				<Provider>
					<Header />
					<FormProvider>{children}</FormProvider>
					<Footer />
				</Provider>
			</body>
		</html>
	);
}
